# 開発環境用

version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/back_code

    working_dir: /back_code
    tty: true

    # ================= docker起動時 =================

    # load env into system
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
   

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/front_code
      - frontend_node_modules:/front_code/node_modules

    working_dir: /front_code
    tty: true

    # ================= docker起動時 =================

    # load env into system
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"

volumes:
  frontend_node_modules: